learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('learning_logs.urls', namespace='learning_logs'))
]

learning_log/learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import re_path

from . import views
# 如果在learning_log
# 下的urls.py里面增加了子路由，并且增加了命名空间，这里要再声明一下app_name才不会出现namespace
# is not registed的错误
app_name = '[learning_logs]'

urlpatterns = [
    # 主页
    re_path(r'^$', views.index, name='index'),
    # 主题
    re_path(r'^topics/$', views.topics, name='topics'),
    # 主题详情
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic')
]

learning_log/learning_logs/models.py
from django.db import models

# Create your models here.
# 模型告诉Django如何处理应用程序中存储的数据
# 在代码层面，模型就是一个类，包含属性和方法

# 下面是创建用户将要存储的主题的模型：


class Topic (models.Model):

    """用户学习的主题"""
    text = models.CharField(max_length=200, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

# 我们需要告诉Django，默认应使用哪个属性来显示有关主题的信息。Django调用方法__str__()来显示模型的简单表示。在这里，我们编写了方法__str__()，它返回存储在属性text中的字符串

# 激活模型
# 要使用模型，必须让Django将应用程序包含到项目中。为此，打开settings.py（它位于目录learning_log/learning_log中），你将看到一个这样的片段，INSTALLED_APPS,把learning_logs加在这个列表中即可

# 定义模型Entry


class Entry(models.Model):

    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=None)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # 我们在Entry类中嵌套了Meta类。Meta存储用于管理模型的额外信息，在这里，它让我们能够设置一个特殊属性，让Django在需要时使用Entries来表示多个条目。如果没有这个类Django将使用Entrys来表示多个条目。

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + '...'

learning_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic
# Create your views here.

def index(request):
    '''学习笔记的主页'''
    return render(request, 'learning_logs/index.html')

def topics(request):
    print(1)
    '''显示所有的主题'''
    topics = Topic.objects.order_by('date_added')
    print(2)
    print(topics)
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    '''显示担个主题及主题下所有的条目'''
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
<p>
  <a href="{% url 'learning_logs:index' %}">Learning Log</a>
  <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html"%}

{% block content%}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</P>
{% endblock content%}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Topic: {{ topic  }}</p>
<p>Entries:</p>
<ul id="">
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added }}</p>
      <p>{{ entry.text | linebreaks  }}</p>
    </li>
  {% empty %}
    <li>There are no entries for this topic yet</li>
  {% endfor %}
</ul>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topics</p>
<ul id="">
  {% for topic in topics %}
  <li class=""><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
  {% empty %}
    <li class="">No topics have been added yet.</li>
  {% endfor %}
</ul>

{% endblock content %}